### ISSUE TITLE
MVP 2: User Authentication Checklist

### ISSUE THREAD

**Issue by samwalker191** [samwalker191/YourTube#2]
# User Auth
## Backend
  - [x] `users` table
  - [x] `User` model
  - [x] `UsersController` / `SessionsController`
  - [x] `show.json.jbuilder` for `users`, `session`
### Ajax Calls
  - [x] `session_api_utils`
    - [x] `createUser`, `createSession`, `destroySession`
### Actions
  - [x] `session_actions`
    - [x] `RECEIVE_CURRENT_USER`, `LOGOUT_CURRENT_USER`, `RECEIVE_ERRORS`, `CLEAR_ERRORS`
    - [x] Action Creators: `receiveCurrentUser`, `logoutCurrentUser`, `receiveErrors`
    - [x] Thunktions: `signup(user)`, `login(user)`, `logout` 
### Reducers
  - [x] `session_reducer`
    - [x] Default: `_nullSession`
    - [x] Cases: `RECEIVE_CURRENT_USER`, `LOGOUT_CURRENT_USER`
  - [x] `users_reducer`
    - [x] Case: `RECEIVE_CURRENT_USER`
  - [x] `session_errors_reducer`
    - [x] Case: `RECEIVE_ERRORS`
  - [x] `entities_reducer`
    - [x] combines `users_reducer`
  - [x] `errors_reducer`
    - [x] combines `session_errors_reducer`
  - [x] `root_reducer`
    - [x] combines `entities_reducer`, `session_reducer`, `errors_reducer`
### Components
  - [x] `SignUpFormContainer` 
    - [x] `mapSTP`: `errors`, `formType: signup` 
    - [x] `mapDTP`: `action: signup(user)`
 - [x] `SignInFormContainer`
    - [x] `mapSTP`: `errors`, `formType: signin`
    - [x] `mapDTP`: `action: signin(user)`
  - [x] `SessionForm`
    - [x] contains form to handlesubmit
    - [x] shows different things based on `formType`
    - [x] displays errors if there are any
    - [x] has demo user button
  - [x] `Header`
    - [x] has sign in button if not logged in
    - [x] has logout button if logged in
### Auth/Protected Routes
  - [x] `routes_api_util`
### Current User
  - [x] bootstrap current user to window
  - [x] add preloaded state with current user to entry file

**Comment by mwmadsen67** [comment]
- [x] Styling
  - [x] When errors are displayed, the form adjusts properly (input boxes move up, sign in/sign up button moves down, and errors are displayed in between)
- [x] Smooth, bug free navigation
  - [x] Login errors clears when switching from login form to sign up form (and vice-versa)
  - [ ] Going to a random route `/#/oweiniouewbrviuwebv` should redirect to either `/`, `/login`, or `/signup`
  - [x] Errors should display for both `/signup` and`/login`.
  - [x] Errors should clear when moving between `/signup` and `/login`.
- [x] Adequate and appropriate seeds
  - [x] Demo Login Works

**Comment by ryan-mapa** [comment]
- [x] style buttons for sign up / login / demo

**Comment by samwalker191** [comment]
Updated styling for sessionForm buttons:
* Renamed 'demo user' button to just 'demo', making the text look less squished
* Made buttons and text within buttons larger, making it easier to read
* Updated font-styling in buttons to match other text

**Comment by ryan-mapa** [comment]
Nice job!
