### ISSUE TITLE
MVP 3: Videos Checklist

### ISSUE THREAD

**Issue by samwalker191** [samwalker191/YourTube#3]
# Videos 
## Backend
- [x] `videos` table
- [x] `active-storage` tables
- [x] Setup AWS, connect to active-storage
- [x] `Video` Model
  - [x] associations: `users`, `active-storage`
- [x] `VideosController`
  - [x] `#index`, `#create`, `#show`, `#update` `#destroy`
    - [x] `#index` should take in a query and get videos that have titles that contain that query
      - [x] default is `''`: this grabs all videos
- [x] `show.json.jbuilder`, `index.json.jbuilder`
### Ajax Calls
- [x] `videos_api_util`
  - [x] `fetchVideos`, `fetchVideo`, `createVideo`, `updateVideo`, `removeVideo`
### Actions
- [x] `videos_actions`
  - [x] `RECEIVE_VIDEOS`, `RECEIVE_VIDEO`, `REMOVE_VIDEO`, `RECEIVE_ERRORS`, `REMOVE_ERRORS`
  - [x] Action Creators: `receiveVideos`, `receiveVideo`, `deleteVideo`, `receiveErrors`, `clearErrors`
  - [x] Thunktions: `fetchVideos`, `fetchVideo`, `createVideo`, `updateVideo`, `removeVideo`
### Reducers
- [x] `videos_reducer`
  - [x] Cases: `RECEIVE_VIDEOS`, `RECEIVE_VIDEO`, `REMOVE_VIDEO`
  - [x] Add to `entities_reducer`
- [x] `video_errors_reducer`
  - [x] Case: `RECEIVE_ERRORS`, `REMOVE_ERRORS`
  - [x] Add to `errors_reducer`
### Components
- [x] `VideoIndexContainer`
  - [x] `mapSTP`: `videos` array
  - [x] `mapDTP`: `fetchVideos`
- [x] `VideoIndex`
  - [x] `fetchVideos` on `componentDidMount`
  - [x] Render each video from `this.props.videos` as a `VideoIndexItem`
 - [x] `VideoIndexItem`
  - [x] Each video should show the following:
    - [x] Img preview that links to `VideoShow`
    - [x] `video.title`
    - [x]  `video.author`
- [x] `CreateVideoFormContainer`
  - [x] `mapSTP`: `video_errors`, `current_user`, `formType: create`
  - [x] `mapDTP`: `createVideo`
- [x] `EditVideoFormContainer`
  - [x] `mapSTP`: `video_errors`, `current_user`, `formType: edit`
  - [x] `mapDTP`: `updateVideo`
- [x] `VideoForm`
  - [x] should have file upload section, along with details input
  - [x] redirects to video index 
- [x] `VideoShowContainer`
  - [x] `mapSTP`: `video = this.state.entities.videos.ownProps.match.params.videoId`, `currentUser`
  - [x] `mapDTP`: `fetchVideo`, `fetchVideos`
- [x] `VideoShow`
  - [x] Shows video player for specific video
  - [x] Contains title, author, description
  - [x] Contains a VideoIndex on the side of the page
  - [x] Contains edit/delete buttons if owner of video

**Comment by samwalker191** [comment]
MVP Functionality Checklist:
 - [x] Videos have a thumbnail that can be chosen when a user is uploading a video
    - [x] Thumbnail can be changed via the video edit form
- [x] Users, logged in or not, can see an index of videos and watch them
- [x] Logged in users can upload new videos, and edit/delete videos they have uploaded
  - [x] Edit button shows up on video show page if user is owner of video
- [x] 'Home' page is an index of videos
- [x] Individual videos are watched on a 'show' page that also includes other videos to navigate to
