### ISSUE TITLE
MVP 5: Comments Checklist

### ISSUE THREAD

**Issue by samwalker191** [samwalker191/YourTube#5]
# Comments
## Backend
- [x] `comments` table
- [x] `Comment` model
- [x] `CommentsController`
  - [x] `#create`, `#destroy`
      - [x] `#create` is nested under videos routes
- [x] update `show.json.jbuilder` for videos to include all comments made for that video
- [x] create `show.json.jbuilder` for comments. To be rendered on creation of new comment.
### Ajax Calls
- [x] `comments_upi_util`
  - [x] `createComment`, `deleteComment`
### Actions
- [x] `RECEIVE_COMMENT`, `REMOVE_COMMENT`
- [x] Action Creators: `receiveComment`, `removeComment`
- [x] Thunktions: `createComment`, `deleteComment`
### Reducers
- [x] `CommentsReducer`
  - [x] Cases: `RECEIVE_COMMENT`, `REMOVE_COMMENT`
  - [x] Add to `EntitiesReducer`
### Components
- [x] `VideoShowContainer`
  - [x] add to `mapSTP`: array of comments associated with the specific video
  - [x] add to `mapDTP`: `createComment`, `deleteComment`
- [x] `VideoShow`
  - [x] Add `CommentsIndex` below Video and video description
    - [x] Each `CommentIndexItem` should contain details of comment and a delete button if current user owns it.
  - [x] Right on top of `CommentsIndex` place `CommentsForm`

**Comment by samwalker191** [comment]
The base functionality is finished, but in order to get likes to work on them I think I need to refactor some of my backend. Comment likes is technically a bonus MVP so I wanted to finish Search before tackling it.

**Comment by mwmadsen67** [comment]
Sounds good.
