### ISSUE TITLE
MVP 6: Search Checklist

### ISSUE THREAD

**Issue by samwalker191** [samwalker191/YourTube#6]
# Search
## Backend
- [x] Make sure `VideosController` `#index` can take in a query and then grabs all videos that have that query in their title. Keep it basic for now.
### Ajax Calls
- [x] Make sure `fetchVideos` can take in a query and that it successfully returns a filtered list of videos
### Actions
- [x] Make sure `fetchVideos` can take in a query that it passes to `APIUtil.fetchVideos`
### Reducers
- [x] Make sure `video_reducer` is working as intended.
### Components
- [x] Add `searchBar` component to `Header`
  - [x] This should redirect/render to the `search/:query` route
  - [x] Most likely will be a form with text input field. Will redirect/render onSubmit
- [x] `SearchVideoIndexContainer` (maybe could reuse `VideoIndexContainer`)
  - [x] `mapSTP`: `videos` array, 
  - [x] `mapDTP`: `fetchVideos`
- [x] `SearchVideoIndex`
  - [x] Should be list of `SeachVideoIndexItem` that link to the video show page
- [x] `SearchVideoIndexItem`
  - [x] Should show the following:
    - [x] `video.title`
    - [x] `video.owner`
    - [x] `video.description`

**Comment by samwalker191** [comment]
This has been pushed to Heroku now. Sidebar is included, but is set to not show up on a video show page. After I add channels/subs I'm going to try to have the sidebar pop up as a modal on the video show page when the hamburger is clicked.
