### ISSUE TITLE
MVP BONUS 1: Number of Plays Checklist

### ISSUE THREAD

**Issue by samwalker191** [samwalker191/YourTube#7]
# Number of Plays
## Backend
- [x] Make sure `videos` has a `views` column, this should default to 0
- [x] Update `show.json.jbuilder` and `index.json.jbuilder` to include `views` in the response
### Ajax Calls
- [x] Nothing to change
### Actions
- [x] Nothing to change
### Reducers
- [x] Nothing to change
### Components
- [x] `VideoIndexContainer`
  - [x] `mapSTP`: Make sure views property is being passed through inside of `videos` array
  - [x] `mapDTP`: No change
- [x] `VideoIndexItem`
  - [x] Each video should show `video.views`
- [x] `VideoShowContainer`
  - [x] `mapSTP`: make sure views is being passed through with video details
  - [x] `mapDTP`: `updateVideo`
- [x] `VideoShow`
  - [x] Add `video.views` 
  - [x] need local state to keep track of video details
  - [x] `componentDidMount` increment views by 1, `updateVideo`, `fetchVideo`
    - [x] This is how YouTube does it allegedly. Could also do it `onPlay` of the video. either way is spammable.
